
export const options = ['goods', 'burger', 'pizza', 'drink'];


export const data = [
    {
        id: 1,
        name: 'super burger',
        img: 'https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/black_and_blue_burger_95881_16x9.jpg',
        price: 100,
        quantity: 0,
        limit: 20,
        select: false,
        category: 'burger',
        status:'sold',
    },
    {
        id: 2,
        name: 'pro burger',
        img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Cheeseburger-3d7c922.jpg',
        price: 150,
        quantity: 0,
        limit: 20,
        select: false,
        category: 'burger',
        status:'available',
    },
    {
        id: 3,
        name: 'extra burger',
        img: 'https://mcdonalds.com.au/sites/mcdonalds.com.au/files/MCD_Category_Burgers_375x268.png',
        price: 180,
        quantity: 0,
        limit: 20,
        select: false,
        category: 'burger',
        status:'available',
    },
    {
        id: 4,
        name: 'italian pizza',
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/7b/99/6f/pizzas-de-ate-40cm-com.jpg',
        price: 300,
        quantity: 0,
        limit: 10,
        select: false,
        category: 'pizza',
        status:'available',
    },
    {
        id: 5,
        name: 'meat pizza',
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/1d/74/13/63/pizzas-garage-medellin.jpg',
        price: 400,
        quantity: 0,
        limit: 10,
        select: false,
        category: 'pizza',
        status:'available',
    },
    {
        id: 6,
        name: 'pivo',
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/b9/6d/b0/nase-rezane-pivo.jpg',
        price: 500,
        quantity: 0,
        limit: 30,
        select: false,
        category: 'drink',
        status:'available',
    },
    {
        id: 7,
        name: 'vino',
        img: 'https://www.tastingtable.com/img/gallery/the-best-way-to-drink-chilled-red-wine/l-intro-1660412521.jpg',
        price: 1000,
        quantity: 0,
        limit: 30,
        select: false,
        category: 'drink',
        status:'available',
    },
    {
        id: 8,
        name: 'vodka',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4zJnVB3ClNwB4qV_mSiepqNfI6eQaidjLyw&usqp=CAU',
        price: 2000,
        quantity: 0,
        limit: 30,
        select: false,
        category: 'drink',
        status:'available',
    },
    {
        id: 9,
        name: 'tequila',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_FnYASy60LXK2iwxu01N6oBpKKEwJ4d6DKg&usqp=CAU',
        price: 3000,
        quantity: 0,
        limit: 30,
        select: false,
        category: 'drink',
        status:'available',
    },
    
]